name: Twitterater
description: Twitterater is a bot that helps you to analyze any Twitter account by showing the percentage of how much positive or negative tweets on there using just the username.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Some important libs
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  string_validator: ^0.1.4
  clipboard_manager: ^0.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
   - assets/images/
  